version: '3'
services:
  back-app:
    # Configuration as before
  front-app:
    image: hectormm24/mlops_td3_front:v2
    ports:
      - "8081:80"
    environment:
      - WS_BACK_URL=http://back-app:5000
volumes:
  back-data:
